# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import imagewrapper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=imagewrapper.models.upload_avatar, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'avatar',
                'verbose_name_plural': 'avatar',
            },
        ),
    ]
