# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 05:24
from __future__ import unicode_literals

from django.db import migrations
import imagewrapper.models
import plugin.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imagewrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=plugin.fields.ThumbnailImageField(upload_to=imagewrapper.models.upload_avatar),
        ),
    ]
